[package]
name = "chinese_clip"
version = "0.1.0"
edition = "2021"

[dependencies]
ort = "=2.0.0-rc.7"
anyhow = "1.0"
image = "0.25"
ndarray = "0.16"
tokenizers = { version = "0.20", default-features = false, features = [ "onig" ] }